Mayowa
Sesughter01/vthCohort2 pull request #10
Opened 2023-08-16 14:54 UTC by MAYII-XCHANGE

Done with the work

2023-08-17 07:54 UTC, Sesughter01 commented on assets/MAYOWA DOM PROJECT 1.png
Please the name of the html file this DOM is for

2023-08-17 07:58 UTC, Sesughter01 commented on class_eight/index.html
Your scope of work did not include adding a header element , your team was only required to work on the section below the header. Remove the header element and its contents then stage commit , push and create a new pull request with the changes made. thank you. well done.

2023-08-17 07:59 UTC, Sesughter01 commented on class_two/index.css
I will view this work and revert shortly. Good work

2023-08-17 08:00 UTC, Sesughter01 commented on class_two/index.html
I will view and revert shortly

2023-08-17 08:00 UTC, Sesughter01 commented on class_two/news-homepage-main/index.html
I will view and revert shortly

2023-08-17 08:02 UTC, Sesughter01 requested changes
Well doe. Make the changes to class_eight as required and indicate the name of the html file your DOM is for. I will view your news-homepage-main project and score you.

2023-08-21 15:23 UTC, MAYII-XCHANGE commented
JAVASCRIPT CLASS WORK

2024-03-20 08:27 UTC, closed without merging