Victorherald
Sesughter01/vthCohort2 pull request #4
Opened 2023-08-02 14:23 UTC by Victorherald

did the markupp

2023-08-02 14:31 UTC, Sesughter01 commented on class_six/GitHub-Mark.png
Good work but add this image to the assets folder in the root

2023-08-02 14:32 UTC, Sesughter01 commented on class_six/Logo_of_Twitter.svg.png
Good try but add this image to assets folder

2023-08-02 14:33 UTC, Sesughter01 commented on class_six/asparagus-2169305_1280.jpg
Add this image to the assets folder

2023-08-02 14:34 UTC, Sesughter01 commented on class_six/football-1396740_1920.jpg
Add to the assets folder remove from here

2023-08-02 14:36 UTC, Sesughter01 commented on class_six/index.html
>          <div id="item1">Header</div>
This element is supposed to hold your logo change the text copy to logo or better if you have a logo place here

2023-08-02 14:37 UTC, Sesughter01 commented on class_six/pancakes-2291908_1280.jpg
Add to the assets folder remove from here

2023-08-02 14:38 UTC, Sesughter01 commented on class_six/salmon-518032_1280.jpg
Add to the assets folder remove from here also use an image of equal size with the other images you have in this div. Good try.

2023-08-02 14:39 UTC, Sesughter01 commented on class_six/vercel.png
Add to the assets folder remove from here

2023-08-02 14:41 UTC, Sesughter01 requested changes
Please take a look at my comments and refactor (adjust) code accordingly

2023-08-02 14:59 UTC, Victorherald commented
added it in asset folder

2023-08-02 15:13 UTC, Victorherald commented
already corrected sir

2023-08-02 15:15 UTC, Victorherald commented
corrected the folders

2023-08-03 06:40 UTC, Sesughter01 commented on assets/GitHub-Mark.png
corrected good work

2023-08-03 06:41 UTC, Sesughter01 commented on assets/Logo_of_Twitter.svg.png
corrected good

2023-08-03 06:41 UTC, Sesughter01 commented on assets/asparagus-2169305_1280.jpg
corrected

2023-08-03 06:42 UTC, Sesughter01 commented on assets/football-1396740_1920.jpg
ok

2023-08-03 06:45 UTC, Sesughter01 commented on assets/images.jpg
I assume this is your logo . It is wrongly positioned it should be the header text was before correct that.
<img width="925" alt="victorh_correctn" src="https://github.com/Sesughter01/vthCohort2/assets/55626468/ab51ffce-c9be-4e21-92b7-3ff3dffe4813">

2023-08-03 06:45 UTC, Sesughter01 commented on assets/pancakes-2291908_1280.jpg
ok good

2023-08-03 06:45 UTC, Sesughter01 commented on assets/salmon-518032_1280.jpg
ok good

2023-08-03 06:46 UTC, Sesughter01 commented on assets/vercel.png
ok

2023-08-03 06:51 UTC, Sesughter01 commented on class_six/index.html
your home, about, contact, login, and register links should be in the header not the side menu. You can put other things you like in the side menu
<img width="786" alt="victorH2_correctns" src="https://github.com/Sesughter01/vthCohort2/assets/55626468/5b6208aa-995f-4bdd-9555-85a276ff995c">

2023-08-03 06:54 UTC, Sesughter01 requested changes
Please adjust your code based on the new corrections please go over the grid layout class notes again

2023-08-03 08:23 UTC, Victorherald commented
adjusted the header logo to the left sir

2023-08-04 14:50 UTC, Sesughter01 commented on class_six/GitHub-Mark.png
Why have you moved this image back to root . You were instructed to keep all your image assets inside the asset folder?

2023-08-04 14:51 UTC, Sesughter01 commented on class_six/Logo_of_Twitter.svg.png
move back to assets folder

2023-08-04 14:52 UTC, Sesughter01 commented on class_six/asparagus-2169305_1280.jpg
move back to assets folder

2023-08-04 14:52 UTC, Sesughter01 commented on class_six/football-1396740_1920.jpg
move back to assets folder

2023-08-04 14:52 UTC, Sesughter01 commented on class_six/football-1396740_1920.jpg
move back to assets folder

2023-08-04 14:57 UTC, Sesughter01 commented on class_six/pancakes-2291908_1280.jpg
move back to assets

2023-08-04 14:58 UTC, Sesughter01 commented on class_six/salmon-518032_1280.jpg
move back to assets

2023-08-04 14:58 UTC, Sesughter01 commented on class_six/vercel.png
move back to assets folder

2023-08-04 14:59 UTC, Sesughter01 reviewed
Please follow the instructions you are given strictly . If you are not sure ask for clarification

2023-08-10 10:23 UTC, Victorherald commented
SIR, here is my progress so far

2023-08-14 11:40 UTC, Victorherald commented
created the javascrippt

2023-08-16 12:28 UTC, Victorherald commented
done the markup

2023-08-16 12:35 UTC, Victorherald commented
done the markup

2023-08-16 12:40 UTC, Sesughter01 commented
Good work on markup

2023-08-16 12:44 UTC, Sesughter01 approved these changes
Great work

2023-08-16 12:45 UTC, merged