did class_five assgnmt and class_six class work
Sesughter01/vthCohort2 pull request #5
Opened 2023-08-02 14:48 UTC by BuchiGold

assignment and classwork

2023-08-02 14:49 UTC, BuchiGold commented
assignmt and classwork

2023-08-04 15:06 UTC, Sesughter01 commented on class_six/food1.avif
please use any of the following file formats : png, jpg for your images

2023-08-04 15:08 UTC, Sesughter01 commented on class_six/food2.avif
same thing for this one

2023-08-04 15:08 UTC, Sesughter01 commented on class_six/food3.avif
same thing here

2023-08-04 15:08 UTC, Sesughter01 commented on class_six/football.avif
same thing here too

2023-08-04 15:09 UTC, Sesughter01 commented on class_six/github.jpg
This is a jpg file this is ok but move it into the assets folder

2023-08-04 15:11 UTC, Sesughter01 commented on class_six/index.html
Your item1 is wrongly positioned and i said to replace the header text with your logo either as text logo or an actual logo.

2023-08-04 15:26 UTC, Sesughter01 commented on class_six/twitter.jpg
move to asset folder

2023-08-04 15:27 UTC, Sesughter01 commented on class_six/vercel.jpg
move to assets folder

2023-08-04 15:28 UTC, Sesughter01 requested changes
Please take a very close look at the corrections made and make changes

2023-08-06 20:41 UTC, BuchiGold commented
made necessary corrections

2023-11-15 09:02 UTC, closed without merging