Sheriff
Sesughter01/vthCohort2 pull request #6
Opened 2023-08-02 15:12 UTC by Bigchevrrr

assignment

2023-08-04 15:33 UTC, Sesughter01 commented on assets/chop.jpg
good your image is in the correct folder

2023-08-04 15:34 UTC, Sesughter01 commented on assets/eat.jpg
ok

2023-08-04 15:34 UTC, Sesughter01 commented on assets/facebook.logo.png
ok

2023-08-04 15:35 UTC, Sesughter01 commented on assets/food.jpg
choose better quality images

2023-08-04 15:35 UTC, Sesughter01 commented on assets/football.logo.png
same thing here

2023-08-04 15:35 UTC, Sesughter01 commented on assets/twitter.logo.png
ok

2023-08-04 15:42 UTC, Sesughter01 commented on assets/vinicom.png
good logo but its positioned wrongly see attached image for correction
<img width="938" alt="sheriff_correctns" src="https://github.com/Sesughter01/vthCohort2/assets/55626468/836ec265-cfe6-47dc-9ac0-241fe7cb7882">

2023-08-04 15:43 UTC, Sesughter01 reviewed
Please carefully note the corrections and make them

2023-08-04 15:44 UTC, Sesughter01 reviewed
make the correctns

2023-08-16 14:53 UTC, Bigchevrrr commented
classwork

2023-08-17 08:04 UTC, Sesughter01 commented on assets/DOM.png
Please indicate the html file this DOM is for. Good job

2023-08-17 09:07 UTC, Sesughter01 commented on class_eight/index.css
I will view and revert to you good job

2023-08-17 09:08 UTC, Sesughter01 commented on class_eight/index.html
good

2023-08-17 09:13 UTC, Sesughter01 requested changes
Please update your class_two news-homepage project

2023-08-17 09:25 UTC, Bigchevrrr commented
pushed sir

2023-11-15 09:02 UTC, closed without merging