commit
Sesughter01/vthCohort2 pull request #7
Opened 2023-08-07 13:39 UTC by feranmi06

have done the classwork

2023-08-07 14:05 UTC, feranmi06 commented
done

2023-08-14 08:05 UTC, Sesughter01 commented on class_one/github logo.png
move this image to assets folder in your root directory

2023-08-14 08:06 UTC, Sesughter01 commented on class_one/vercel logo.png
move image to assets folder in root

2023-08-14 08:06 UTC, Sesughter01 commented on class_one/vercel logo.png
move image to assets folder in root

2023-08-14 08:07 UTC, Sesughter01 commented on class_six/amala.jfif
change this file to a png or jpg or jpeg file  and move it to root folder

2023-08-14 08:08 UTC, Sesughter01 commented on class_six/football.jfif
change this file to a png or jpg or jpeg file and move it to root folder

2023-08-14 08:08 UTC, Sesughter01 commented on class_six/fried rice.jfif
change this file to a png or jpg or jpeg file and move it to root folder

2023-08-14 08:08 UTC, Sesughter01 commented on class_six/github logo.png
change this file to a png or jpg or jpeg file and move it to root folder

2023-08-14 08:10 UTC, Sesughter01 commented on class_six/index.html
Good conversion of copy text to markup

2023-08-14 08:10 UTC, Sesughter01 commented on class_six/indomie.jfif
change this file to a png or jpg or jpeg file and move it to root folder

2023-08-14 08:11 UTC, Sesughter01 commented on class_six/twitter logo.png
move this image to root folder

2023-08-14 08:11 UTC, Sesughter01 commented on class_six/vercel logo.png
move this image to root folder

2023-08-14 08:13 UTC, Sesughter01 reviewed
Please make the changes accordingly if you have any issues send me a private message on whatsapp

2023-08-16 13:11 UTC, feranmi06 commented
have done it

2023-08-17 07:35 UTC, Sesughter01 commented on assets/DOM.jpg
Fair try but your DOM try is not totally correct . The Body cannot have an href child because href is not an element its an attribute. Make the necessary corrections to your DOM

2023-08-17 07:43 UTC, Sesughter01 commented on class_eight/index.html
Your html markup is not ok . The fishfarmclub logo  is supposed an svg that you get from the figma file to be exactly the same . Also you are supposed to wrap the logo and the join club button inside a header element like this
`
  <header>
       <img src="./logo.svg" alt="fishfarmclub logo" />

         <div>
               <a href="#">Join Club</a>
         </div>
   </header>
`

2023-08-17 07:51 UTC, Sesughter01 requested changes
Quickly make changes to your class_eight markup as suggested

2023-08-21 16:10 UTC, feranmi06 commented
done sir

2023-08-25 14:37 UTC, feranmi06 commented
done sir

2023-11-15 09:02 UTC, closed without merging